version: '3.7'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elasticsearch:/usr/share/elasticsearch/data
    expose:
      - 9200
    environment:
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/config/metricbeat.template.json:/usr/share/logstash/config/metricbeat.template.json
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000/tcp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      AWS_CBOR_DISABLE: "true"
      AWS_ACCESS_KEY_ID: "not-needed"
      AWS_SECRET_ACCESS_KEY: "not-needed"
      AWS_DEFAULT_REGION: "eu-west-1"
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./kibana/log/kibana.log:/var/log/kibana.log
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  localstack:
    image: localstack/localstack:0.11.0
    ports:
      - "5001:4566" # localstack's service proxy endpoint
    expose:
      - 4566
    environment:
      SERVICES: cloudformation,kinesis,dynamodb
      DEFAULT_REGION: eu-west-1
      KINESIS_ERROR_PROBABILITY: 0.0
      # This is because https://github.com/awslabs/amazon-kinesis-producer
      # (used by logstash kinesis output plugin) only supports connection via HTTPS.
      # It's possible this might need to be configurable in the future,
      # if logs are sent to Kinesis locally using other methods.
      USE_SSL: "true"

volumes:
  elasticsearch:
