#!/usr/bin/env bash

set -e

LOCALSTACK_ENDPOINT=http://localhost:5001
STREAM_NAME=local-elk-logging-kinesis-stream

# provide dummy credentials for the aws cli, they're not used in localstack
export AWS_ACCESS_KEY_ID=not-needed
export AWS_SECRET_ACCESS_KEY=not-needed
export AWS_DEFAULT_REGION=eu-west-1
export AWS_PAGER=""

startLocalStack() {
  docker-compose up -d localstack
  echo "waiting for localstack to launch on $LOCALSTACK_ENDPOINT"
  while ! curl -s $LOCALSTACK_ENDPOINT >/dev/null; do
    sleep 1 # wait for 1 second before check again
  done
  echo " localstack launched"
}

setupLocalKinesis() {
  echo "creating kinesis stream $STREAM_NAME"
  currentStreams=$(aws kinesis list-streams --endpoint-url $LOCALSTACK_ENDPOINT)
  exists=$(echo "$currentStreams" | jq -r ".StreamNames[] | select(. == \"$STREAM_NAME\")")

  if [[ -z $exists ]]; then
    aws --endpoint-url=$LOCALSTACK_ENDPOINT kinesis create-stream --shard-count 1 --stream-name "$STREAM_NAME"
    echo "  created local kinesis stream $STREAM_NAME"
  else
    echo "  skipping as stream $STREAM_NAME exists"
  fi
}

startLocalELK() {
  docker-compose up -d elasticsearch logstash kibana
}

startLocalStack
setupLocalKinesis
startLocalELK

echo "local-elk started. It may take a little while to initialise..."
echo "  local-elk will be available on https://logs.local.dev-gutools.co.uk"
